### ISSUE TITLE
提示有错误

### ISSUE THREAD

**Issue by FDKPIBC** [zhangjh/chromeExt#1]
非莆田系医院都弹窗提示正在访问疑似莆田系医院网站
我访问一个新浪都弹窗了。。。
网页:http://news.sina.com.cn/s/wh/2016-05-03/doc-ifxrtzte9923216.shtml

**Comment by zhangjh** [comment]
@FDKPIBC  嗯，匆忙完成的，目前的判断逻辑还是比较弱的，你可以看下，这个case是因为检测的正则里面有"男子|女子"，这个新闻的标题里也包含“男子”。。应该匹配“男子医院”

**Comment by zhangjh** [comment]
已经fix，修改了检测逻辑，先判断title是否包含“医院”然后再检测是否匹配莆田系医院特征字段
